---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      name: petclinic
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: sundaylawal/cloudjerk:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service 
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  selector:
    app: petclinic
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
