---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinicapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinicapp
  template:
    metadata:
      name: petclinicapp
      labels:
        app: petclinicapp
    spec:
      containers:
      - name: petcliniccontainer
        image: sundaylawal/cloudjerk:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: petclinicapp
  labels:
    app: petclinicapp
spec:
  selector:
    app: petclinicapp
  type: NodePort
  ports:
  - nodePort: 31113
    port: 80
    targetPort: 8080
