apiVersion: apps/v1
kind: Deployment
metadata:
  name: petapp-deployment
  labels:
    app: petapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petapp
  template:
    metadata:
      labels:
        app: petapp 
    spec:
      containers:
      - name: petappserver
        image: sundaylawal/cloudjerk:latest
        ports:
        - containerPort: 8080
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: petapp-service
spec:
  selector:
    app: petapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31600
