--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: pet-clinic
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: pet-clinic
  strategy: 
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app: pet-clinic
    spec: 
      containers:
       - name: pet-clinic
         image: 'sundaylawal/cloudjerk:2'
         ports:
            - containerPort: 8080
              protocol: TCP
