---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic-app
  template:
    metadata:
      name: petclinic-pod
      labels:
        app: petclinic-app
    spec:
      containers:
      - name: petclinic-container
        image: sundaylawal/cloudjerk:2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: petclinic-svc
  labels:
    app: petclinic-app
spec:
  selector:
    app: petclinic-app
  type: NodePort
  ports:
  - nodePort: 31113
    port: 80
    targetPort: 80
